server:
  port: 8888

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/Work/native-file-repo
        git:
          uri: https://github.com/dmsgp6598/spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

